server:
  port: 9090

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:/Users/ricop/Documents/proj-agenda-micro-services/proj-config/arquivos-configuracao
          
